-- =========================================================
-- SCRIPT DE MIGRACIÓN: PostgreSQL (efmbseguros.sql) -> MySQL / MariaDB (XAMPP)
-- Base de datos: segurosmab
-- =========================================================

USE `segurosmab`;

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET character_set_connection = utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `contact_messages`;
TRUNCATE TABLE `policies`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `companies`;

-- =========================================================
-- 1. TABLA: companies
-- =========================================================
INSERT INTO `companies` (`id`, `nombre`, `nit`, `direccion`, `telefono`, `email`, `logo_url`, `color_primario`, `color_secundario`, `isactive`, `created_at`) VALUES (1, 'segurosmab', '10001', 'Cra 72 P N° 43 A - 11 sur', '3108586624', 'mabconsultores@gmail.com', '/uploads/logos/logo-1768269350616-802023561.jpg', '#631025', '#4c55d3', 1, '2026-01-12 20:55:50.630129');
INSERT INTO `companies` (`id`, `nombre`, `nit`, `direccion`, `telefono`, `email`, `logo_url`, `color_primario`, `color_secundario`, `isactive`, `created_at`) VALUES (2, 'segurosferrer', '10002', 'Calle 46 sur N° 72 N  - 59 Boita', '3142999274', 'padafe6541@gmail.com', '/uploads/logos/logo-1768323177274-12154620.jpg', '#631025', '#4c55d3', 1, '2026-01-13 11:52:57.280717');

-- =========================================================
-- 2. TABLA: users
-- =========================================================
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (5, 'Erwin Alirio Ferreira Rojas', '91250451', 1, 'padafe654@gmail.com', 'Calle 43 sur # 72 N - 59', '$2b$10$TRxgeaJ.NLGJtWttntAXyuPYXuQ6urJ6E/cOir51tZSiNL0uO1W1m', 'Bogotá D. C', '3228760242', 'Natural', 'Erwin Alirio Ferreira Rojas', '1965-05-01', 'super_user', NULL, NULL, NULL);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (4, 'David Sebastián Ferreira', '1021247598', 1, 'davidferrer144@gmail.com', 'CRA 72P N 43A - 11 sur', '$2b$10$kv8nb5ZuE87ilvDURHGSRuWLn9xafzfkRKWBq0OmsEH1kzCycqEMq', 'BOGOTA D. C.', '3113731558', 'Personal y Natural', 'David Ferreira', '1999-09-11', 'user', NULL, NULL, 1);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (10, 'Carmen García Ferreira', '91256321', 1, 'carmen2001@hotmail.com', 'Soacha ciudad verde', '$2b$10$kp2jn2yLkvAAobVXx2rrIuvAzVOzoD8HiUd8pCxhmL0ZtrJxg82EK', 'Soacha', '6017904289', 'Comercio aduanas', 'Vilma mejía', '2001-04-29', 'user', NULL, NULL, 1);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (7, 'Ruth Ferreira', '913254514', 1, 'ruthferreirarojas11@gmail.com', 'Soacha ciudad verde', '$2b$10$Gxf18qa/xKYxnrlrtRg0eOxPRmVZngGk/hbG8vqUtMk04i886TO1K', 'Soacha', '6017904288', 'Familiar', 'Erick Pérez', '1966-01-06', 'user', NULL, NULL, NULL);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (3, 'Mario Arrieta', '32145687', 1, 'mar@gmail.com', 'Calle 9 # 3 - 21', '$2b$10$2ueEXoUnaCFBnYR/TKNE/.TUnVo7iFa9YQYeC9NICM0hQosK9mmZu', 'Bucaramanga', '3112564741', 'Estadistica', 'Mario Arrieta', '1995-05-09', 'user', NULL, NULL, 1);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (2, 'Miguel Angel Bernal', '912356245', 1, 'mabconsultores@gmail.com', 'Cra 72P # 43 A - 11', '$2b$10$y4mZKFBiPRv4KG1QvMVRjOwSZCiBuHrzRLUJaAAKnJ8RO45SaBX.G', 'Bogotá D. C', '3026603858', 'Asesor seguros', 'Migel Bernal', '1968-05-05', 'admin', NULL, NULL, 1);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (6, 'Marlon Suarez', '7521410', 1, 'marsua96@gmail.com', 'Calle 72 B N° 21 A - 21 sur Giron Santander', '$2b$10$uUZW.gZREpJZPL/Mu6dHjuuX1Tl/Hm7zCTADvotEq/aRmlyyX2hTC', 'Bucaramanga', '3113251458', 'Transporte', 'Isabel Ferreira', '2026-01-12', 'user', NULL, NULL, NULL);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (8, 'Carol Jimenez', '3211145287', 1, 'carol21@hotmail.com', 'Calle 45 #72R- 61 Barrio Boita (Kennedy)', '$2b$10$RSk1mDpO.d3X5XAuLy16x.qTfxj336ggmYDksdgjnvYX7RTiuTlvq', 'BOGOTA D.C.', '3211245012', 'Comercial abarrotes', 'Carol Jimenez Ramirez', '1975-01-03', 'user', NULL, NULL, 1);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (1, 'Vilma Mejía Sanguino1', '63551221', 1, 'padafe6541@gmail.com', 'Cra 72K # 3 - 27', '$2b$10$10.KVw5zVYXpYoNrWkkJRuSsBJtdNuNcbRlC940uQz8unrGBzpkDy', 'Bogotá D. C', '3026603858', 'Veterinaria 3', 'Vilma Mejía Sanguino', '2021-04-26', 'user', NULL, NULL, 1);
INSERT INTO `users` (`id`, `user_name`, `documento`, `isactive`, `email`, `direccion`, `user_password`, `ciudad`, `telefono`, `actividad_empresa`, `representante_legal`, `fecha_nacimiento`, `roles`, `reset_password_token`, `reset_password_expires`, `company_id`) VALUES (9, 'Gabriel Bernal Ferreira', '9921451', 1, 'gaboberfer@gmail.com', 'Cra 72 P N° 43 A - 11 sur', '$2b$10$UQYON8.t6LPWnU.JfAGzyuJb0VSqSJXVAbCs0HhoFR3yxUkL67U4a', 'BOGOTA D. C.', '3041010805', 'Seguros', 'Miguel Bernal', '2005-04-11', 'admin', NULL, NULL, 1);

-- =========================================================
-- 3. TABLA: policies
-- =========================================================
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (2, 'A-102', 'auto', '2025-12-06', '2026-02-03', 'robo y accidente', 'Mafre', '3211234560', 100000000, 'AFK-101', 'BZN - 321', '5 - 1.6 - 6', 'Bogotá D.C', 120000000, 5000000, 1250000, '2025', 'Privado', 'automovil', 'Asd321321', 'Asd321321', 'Mario Arrieta y Padres', 1, 3, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (6, 'A-105', 'Riesgo Robo', '2024-12-23', '2026-02-03', 'robo y accidente grado', 'Seguros del estado', '#611', 120000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 4, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (5, 'A-104', 'Contra incendios Total 3', '2024-12-25', '2025-12-28', 'robo y accidente', 'Mafre 1', '3211234561', 100000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (1, 'A-101', 'Cliente Auto 3', '2024-12-24', '2025-12-27', 'Robo y accidente', 'Seguros del estado', '3112521415', 5000, 'C-1001', 'BKZ - 489', '2.5 ton, 1.5 full inyección y 5 pasajeros', 'Bogotá D. C - Bogotá D. C', 25000000, 5000000, 30000000, 'Renault - 19 - 2007', 'Orivado', 'automovil', '3214568978', '3214568978', 'Erwin Ferreira Y Vilma Mejía Sanguino', 1, 1, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (8, 'A-108', 'Vida', '2026-01-12', '2027-01-12', 'Accidente y secuestro', 'Seguros Bolivar', '#710', 125000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 8, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (3, 'A-103', 'Vida', '2026-12-03', '2026-02-03', 'Robo e incendio', 'Mafre', '#115', 10000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (9, 'A-110', 'Riesgo Robo', '2025-02-05', '2026-02-04', 'robo y accidente', 'Seguros Bolivar', '#601', 25000001, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1);
INSERT INTO `policies` (`id_policy`, `policy_number`, `tipo_poliza`, `inicio_vigencia`, `fin_vigencia`, `tipo_riesgo`, `compania_seguros`, `telefono_asistencia`, `valor_asegurado`, `cod_fasecolda`, `placa`, `tonelaje_cilindraje_pasajeros`, `departamento_municipio`, `valor_comercial`, `valor_accesorios`, `valor_total_comercial`, `modelo`, `servicio`, `tipo_vehiculo`, `numero_motor`, `numero_chasis`, `beneficiario`, `notificada`, `user_id`, `company_id`) VALUES (7, 'A-107', 'Vida', '2026-01-11', '2026-01-27', 'Accidente y robo', 'Mapfre', '#611', 200000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 7, 2);

-- =========================================================
-- 4. TABLA: contact_messages
-- =========================================================
INSERT INTO `contact_messages` (`id`, `nombre`, `email`, `asunto`, `mensaje`, `created_at`, `leido`, `respondido`, `respuesta`, `responded_at`, `user_id`, `responded_by`, `company_id`) VALUES (1, 'David Sebastián Ferreira', 'davidferrer144@gmail.com', 'Renovar poliza', 'Miguel Ángel, este es un mensaje de prueba.', '2026-01-12 22:42:59.291589', 0, 0, NULL, NULL, 4, NULL, 1);

SET FOREIGN_KEY_CHECKS = 1;
